import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import {  useCallback } from "react";
import styles from "../styles/Home.module.css";
import { useAuthentication, Login, Logout } from "@/hooks/authentication";
import { Button, Typography } from "@mui/material";
import GoogleIcon from '@mui/icons-material/Google';


const Home: NextPage = () => {
  const { currentUser } = useAuthentication();
  const router = useRouter();

  const  LoginOrGoToDashboard= useCallback(() => {
    if (currentUser) {
      router.push("/dashboard");
      return
    }
    Login().then((_res) => {
              console.log(_res)
              router.push("/dashboard")
           })
           .catch((e) => alert(e));

  }, [currentUser, router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1" component="h1" gutterBottom sx={{ fontWeight: 'bold' }}>
          Welcome to SendGM
      </Typography>

        <Button
          variant="contained"
          size="large"
          onClick={() => {
            LoginOrGoToDashboard();
          }}
          startIcon={<GoogleIcon />}
          sx={{ fontWeight: 'bold', fontSize: '1.2rem' }}
        >
          Google でログイン
        </Button>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export default Home;
